print("Ваши фамилия, имя?")
A = (input())
B = (input())
print("Сколько вам лет?")
C = (input())
print("Где вы живете")
D = (input())
print("ваши фамилия, имя -", A, B)
print("Ваш возраст - ", C)
print("Вы живете в -", D)